name: HelixOS CMake builder

on:
  push:
    branches: [ "v0.0.1-dev" ]
  pull_request:
    branches: [ "v0.0.1-dev" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run:
        sudo apt-get update
        sudo apt-get install gcc-aarch64-linux-gnu cmake mtools gdisk qemu-system-aarch64 direnv

    - name: Configure HelixOS
      run: 
        # Configure direnv (needed for the HelixOS system)
        echo "eval \"$(direnv hook bash)\"" >> ~/.bashrc && source ~/.bashrc

        cmake -S ${{github.workspace}} -B ${{github.workspace}}/build

    - name: Build HelixOS
      run: 
        cmake --build ${{github.workspace}}/build
