name: HelixOS CMake builder

on:
  push:
    branches: [ "v0.0.1-dev" ]
  pull_request:
    branches: [ "v0.0.1-dev" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install deps
      run: |
        sudo apt-get update 
        sudo apt-get install gcc-aarch64-linux-gnu cmake mtools gdisk qemu-system-aarch64 direnv

    - name: Configure HelixOS
      run: |
        eval "$(direnv hook bash)"
        direnv allow ${{github.workspace}}

        cmake -S ${{github.workspace}} -B ${{github.workspace}}/build

    - name: Build HelixOS
      run: |
        eval "$(direnv hook bash)"
        direnv allow ${{github.workspace}}
        
        cmake --build ${{github.workspace}}/build
